repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/psf/black
  #   rev: 21.9b0
  #   hooks:
  #     - id: black
  #     language_version: python3
  #     exclude: (^venv)
  # - repo: https://github.com/jorisroovers/gitlint
  #   rev:  v0.15.1
  #   hooks:
  #     - id: gitlint
